spring:
  mvc:
    view: # 이제 JSP 파일은 src/main/webapp/WEB-INF/views/ 경로에 두면 됨
      prefix: /WEB-INF/views/
      suffix: .jsp

# 개발 중 JSP 페이지 변경 시 서버를 재시작하지 않아도 브라우저를 새로고침하면 반영됨
server:
  servlet:
    jsp:
      init-parameters:
        development: true
